[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
model.workspace = true
http.workspace = true

egui.workspace = true
egui_extras.workspace = true
serde_json.workspace = true
serde.workspace = true
itertools.workspace = true
eframe.workspace = true
